// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfDtQJDmY3h0dysAxM2WribdWGYjyzJ8',
    appId: '1:448927628217:web:25e217ef275a8cccf89468',
    messagingSenderId: '448927628217',
    projectId: 'flutter-firebase-provide-fcd76',
    authDomain: 'flutter-firebase-provide-fcd76.firebaseapp.com',
    storageBucket: 'flutter-firebase-provide-fcd76.appspot.com',
    measurementId: 'G-KJ51XVLG1C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYR1uTEUJ07gorP0eHWapwnX-iHCkk6FU',
    appId: '1:448927628217:ios:cbb093a06bee9c1af89468',
    messagingSenderId: '448927628217',
    projectId: 'flutter-firebase-provide-fcd76',
    storageBucket: 'flutter-firebase-provide-fcd76.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYR1uTEUJ07gorP0eHWapwnX-iHCkk6FU',
    appId: '1:448927628217:ios:cbb093a06bee9c1af89468',
    messagingSenderId: '448927628217',
    projectId: 'flutter-firebase-provide-fcd76',
    storageBucket: 'flutter-firebase-provide-fcd76.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2AJhEV0gm56iHVaXjsnllrLmCvRPnZok',
    appId: '1:448927628217:android:1e8e2a7174a1fba8f89468',
    messagingSenderId: '448927628217',
    projectId: 'flutter-firebase-provide-fcd76',
    storageBucket: 'flutter-firebase-provide-fcd76.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnfDtQJDmY3h0dysAxM2WribdWGYjyzJ8',
    appId: '1:448927628217:web:d4bd3ba02817362cf89468',
    messagingSenderId: '448927628217',
    projectId: 'flutter-firebase-provide-fcd76',
    authDomain: 'flutter-firebase-provide-fcd76.firebaseapp.com',
    storageBucket: 'flutter-firebase-provide-fcd76.appspot.com',
    measurementId: 'G-0DF2E6G6B6',
  );
}
